### ISSUE TITLE
LoadLibraryW

### ISSUE THREAD

**Issue by deprale** [nefarius/Injector#1]
General Error:
Call to LoadLibraryW in remote process failed.

**Comment by nefarius** [comment]
![](http://i0.kym-cdn.com/photos/images/facebook/000/158/326/9148130.jpg)

**Comment by gaveitatry02** [comment]
I had the same error when I used the Injector (64-bit).  But when I switched to the Inject (32-bit), the error went away.

**Comment by nefarius** [comment]
You can not inject a 32-Bit lib in a 64-Bit process and vice versa. That's common knowledge...
