### ISSUE TITLE
DLL gets injected but does not work

### ISSUE THREAD

**Issue by ozanyasindogan** [nefarius/Injector#11]
Hello!  :)

I built with default settings the library and injected it successfully to csgo.exe process but after pressing INS key,
nothing comes up. Is the cheat still working? Also which injector you use to use on github, would like to see the
code before using it. 

Thanks,

Ozan.

**Comment by nefarius** [comment]
This... isn't a cheat. It's a general purpose DLL injector.

**Comment by ozanyasindogan** [comment]
Damn, sorry. I was trying to use your injector for some other software:))) I mistakenly wrote it here :)
