### ISSUE TITLE
Error When Building

### ISSUE THREAD

**Issue by VangaurdGame** [nefarius/Injector#13]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2220	the following warning is treated as an error	Injector	C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30401\include\xstring	2575	
Warning	C4244	'argument': conversion from 'wchar_t' to 'const _Elem', possible loss of data	Injector	C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30401\include\xstring	2575

**Comment by nefarius** [comment]
That's just a warning but I will check it out anyway and see what it complaints about, thanks!

**Comment by VangaurdGame** [comment]
thanks

it also didnt build because of it

**Comment by nefarius** [comment]
> thanks
> 
> it also didnt build because of it

You can disable the compiler setting that warnings are treated as errors as a workaround.

**Comment by nefarius** [comment]
[Always nice to see weird errors popping up](https://docs.microsoft.com/en-us/answers/questions/194687/warning-c4244-vs-2019.html) 😬

**Comment by VangaurdGame** [comment]
they should also make it like understanable to read aND FIX errors

**Comment by haseeb-heaven** [comment]
Go to project settings -> C/C++ -> All options -> Search **"Treat warnings"** -> then select **NO**

**Comment by nefarius** [comment]
Not worth looking into further since it's an easy fix to just ignore the warning.

**Comment by VangaurdGame** [comment]
i just dont use vscode so its kinda confusing

**Comment by nefarius** [comment]
What has VS Code to do with any of this? This solution is for Visual Studio Community/Professional/Enterprise and as mentioned, just ignore warnings and it builds just fine, not worth the investment.
