### ISSUE TITLE
Flag to make everything goes silent

### ISSUE THREAD

**Issue by galpt** [nefarius/Injector#14]
I'm working on a program that uses this injector programmatically.

If only there's a flag to make everything goes silent (e.g. `-s` for silent mode).
But it's not a big deal tho'.

**Comment by nefarius** [comment]
What EULA confirmation? You mean the copyright header? I'd expect that the least to be there to give credit to the authors. That's how FOSS works.

**Comment by galpt** [comment]
Ahh no, don't mind the eula confirmation, I think it's because I'm using both [handle.exe](https://docs.microsoft.com/en-us/sysinternals/downloads/handle) from Microsoft and your injector at the same time,
so I thought the eula was from the injector.

Anyway I don't have any problems again with both programs and this `-s` silent mode is not a big deal.
So, I'm closing this issue. Thanks in advance!
