### ISSUE TITLE
I cant inject it into a process with spaces

### ISSUE THREAD

**Issue by DXXNS** [nefarius/Injector#17]
I simply cant inject a dll into a process with spaces in the name

**Comment by nefarius** [comment]
Please provide more details as this has been resolved a long time ago, see #2.

**Comment by DXXNS** [comment]
Ooopsi i am sorry

**Comment by nefarius** [comment]
So do you still have that problem or...?

**Comment by Creative-Difficulty** [comment]
@DXXNS How did you solve this? pls update

**Comment by nefarius** [comment]
> @DXXNS How did you solve this? pls update

Read the linked issue #2, this has been fixed a long time ago, simply use the latest release...
