### ISSUE TITLE
Injection fails when process name contains spaces

### ISSUE THREAD

**Issue by Pokerkoffer** [nefarius/Injector#2]
Hi,
first of all, thanks for this little tool.

However, injection fails when trying to inject into a process with spaces.

Neither `-n My process` nor `-n "My Process.exe"` works.

 ```
C:\>Injector.exe -n My Process.exe -i C:\My.dll
Injector x86 [Version 20180821]
Copyright (c) 2009 Cypher, 2012-2018 Nefarius. All rights reserved.

General Error:
Could not find process.
```

**Comment by Aemony** [comment]
Can confirm. Sorta annoying having to resort to alternative measures every now and then.

**Comment by nefarius** [comment]
Whoopsie, will have a look 😄

**Comment by Aemony** [comment]
Thanks for taking a look at it. Seems it affects both when trying to inject using process name as well as window name.

**Comment by nefarius** [comment]
Finally came around to fix it, new release is up!

**Comment by nefarius** [comment]
Confirmed to work so I'll allow myself to close the issue.

**Comment by Aemony** [comment]
Thanks for fixing it!
