### ISSUE TITLE
can't eject a dll, event match case.

### ISSUE THREAD

**Issue by ghggn** [nefarius/Injector#20]
oepn an app(wechat.exe), and it's dll list show like this(windows Resource Monitor)
![Snipaste_2023-09-20_18-17-04](https://github.com/nefarius/Injector/assets/129544540/71a0a8fd-cb64-453f-b9e0-2e4c7c7be085)
then i inject a dll into this app by pid
![Snipaste_2023-09-20_18-18-05](https://github.com/nefarius/Injector/assets/129544540/d1e5f0fd-1a0c-413d-8f20-8f2e887e2198)
it success and in windows Resource Monitor we can find it .
![Snipaste_2023-09-20_18-18-14](https://github.com/nefarius/Injector/assets/129544540/8c2a66ab-3126-4c4d-9a25-079ffc37a8c9)
but 
i cant eject this dll anymore .
![Snipaste_2023-09-20_18-18-57](https://github.com/nefarius/Injector/assets/129544540/d34d428e-446b-4d54-8cb9-c88f6288f9bb)

**Comment by nefarius** [comment]
Try just the dll name, without the path.

**Comment by ghggn** [comment]
i already do that ,  you can see the last pic , i use dll name only and full path . there has two command and all failed .

**Comment by nefarius** [comment]
Ah, correct. Odd, I'll see if I can reproduce and fix 🤞

**Comment by ghggn** [comment]
I eject a dll which injected by another process, that is ListaryHook64.dll in the above screenshot, and I can successfully eject it.
I also modified the source code to output the name and path of the dll when ejecting, and there is no wxhelper in list.
This is the link of wxhelper source code, if you are interested, maybe it will make help for solve the problem!
https://github.com/ttttupup/wxhelper

**Comment by nefarius** [comment]
@ghggn does it work with an earlier version? Like [v1.1.12](https://github.com/nefarius/Injector/releases/tag/v1.1.12)?

**Comment by ghggn** [comment]
it not work too

**Comment by nefarius** [comment]
@ghggn please try the latest master build.

**Comment by ghggn** [comment]
still not work

**Comment by nefarius** [comment]
OK thx for the feedback, will continue investigating.

**Comment by nefarius** [comment]
> still not work

I recommend you [step through here](https://github.com/nefarius/Injector/blob/d748931e2b2d85c84d80e8e94571727fc81e75df/Injector/Injector.cpp#L61) with the debugger and see what kind of strings you're getting back in the comparison.
