### ISSUE TITLE
Problem in 64-bit environment

### ISSUE THREAD

**Issue by ghost** [nefarius/Injector#22]
In a 64-bit environment (Win64), DWORD is a 32-bit unsigned integer type, while HMODULE, which is essentially a pointer, is 64 bits long.

```c
HMODULE LoadLibraryW(
  [in] LPCWSTR lpLibFileName
);

DWORD WINAPI ThreadProc(
  _In_ LPVOID lpParameter
);

BOOL GetExitCodeThread(
  [in]  HANDLE  hThread,
  [out] LPDWORD lpExitCode
);
```

https://github.com/nefarius/Injector/blob/4e0e14ad8f2aea4a6ca6b3d4220569d39b4adbf8/Injector/Injector.cpp#L97-L98

For instance, when a Dll is loaded with low double-word of base address being zero, false runtime error is thrown.

**Comment by nefarius** [comment]
Not sure I'm following, the api docs of GetExitCodeThread say nothing about different behaviour on different architectures?

**Comment by nefarius** [comment]
Ah, because the HMODULE of LoadLibraryW gets cast into a 32bit DWORD behind the scenes, now I get it.

I doubt this error has ever popped up before so IDK how big of a deal it is...

**Comment by fredemmott** [comment]
> For instance, when a Dll is loaded with low double-word of base address being zero, false runtime error is thrown.

as x64 and Arm64 (in windows) are little-endian, it's non-zero *high* bits that mess this up:

```C++
#include <iostream>
#include <Windows.h>

int main() {
        HMODULE handle {reinterpret_cast<HMODULE>(1)};
        HMODULE handle2 {reinterpret_cast<HMODULE>(1 << 32)};
        DWORD value { };
        DWORD value2 { };
        value = *reinterpret_cast<DWORD*>(&handle);
        std::cout << sizeof(handle) << std::endl << value << std::endl << value2 << std::endl;
        return 0;
}
```

```
8
1
0
```

**Comment by fredemmott** [comment]
Ah, sorry, you're right, I need a coffee and to wake up >_< non-zero high bits are what's needed for an incorrect complete HMODULE, but zero low bits are what's needed for a bad bool conversion in this logic.

**Comment by fredemmott** [comment]
Doesn't fundamentally change the issue, but just for some context, there are some constraints on these values - they are literally pointers to the DLL's address space, not an arbitrary 64-bit value:

https://learn.microsoft.com/en-us/windows/win32/dlls/dllmain

> A handle to the DLL module. The value is the base address of the DLL. The HINSTANCE of a DLL is the same as the HMODULE of the DLL, so hinstDLL can be used in calls to functions that require a module handle.
