### ISSUE TITLE
How to remove this HELP

### ISSUE THREAD

**Issue by Yosh1kageK1ra** [nefarius/Injector#3]
i dont know anything about windows script
helpp 

![image](https://user-images.githubusercontent.com/45335047/64874408-923e2580-d668-11e9-9ff7-b0b53ddf8f72.png)

**Comment by nefarius** [comment]
And what makes you think this dialog has anything to do with this project, mate?

**Comment by Yosh1kageK1ra** [comment]
Thx man I got it fixed
