### ISSUE TITLE
How do I run this on crossover?

### ISSUE THREAD

**Issue by atleeruy220** [nefarius/Injector#32]
I tried to use this, but I don't know why it doesn't work.
https://www.unknowncheats.me/forum/other-games/668834-fake-liars-bar-internal.html

I see your tool running in crossover here.
https://www.unknowncheats.me/forum/grand-theft-auto-v/653442-injection-gta-wine-crossover.html

**Comment by nefarius** [comment]
This is a bug tracker, not a help desk for script kiddies.
