### ISSUE TITLE
Will this injector program run in the background on my computer?

### ISSUE THREAD

**Issue by gaveitatry02** [nefarius/Injector#4]
I play games on Steam, and I don't want Steam thinking that I am cheating and injecting dlls into games.  Because if they think that, I could get banned.  I only want to inject a dll into a non-game program that I use so that I can remove their ads without spending money that I don't have because I am on a limited income.

Currently, I am using a program called Process Hacker, but it is a bit tedious.  I have Process Hacker pinned to the taskbar for easy access, when I wish that I could free up space on my taskbar.  Then I have to click the taskbar icon to launch the program.  Then I have to type in the Search Processes search box for the program that I want to inject.  Then I have to wait a while for the search results to appear.  Then I have to right click a search result and select 'Miscellaneous'.  Then I have to select 'Inject DLL'.  Then I have to select the dll that I want to inject and confirm.  That's a lot of steps.

I would just like to use a macro.  Like press F1 and have it automatically inject the dll into the program.  Using a bat file or something similar.

I'm just worried that the program will run in the background or something.  I need it to do its job, inject the dll, and then close out completely.  Will this program do that?  Thanks in advance.

**Comment by nefarius** [comment]
It's not in any way my responsibility what you do with the program and what possible causes it could provoke, especially with games.
